// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc33S_7wn6D842pf4nvmpRYnGYNvFBpDo',
    appId: '1:217858776772:android:e2a537517fc7da8bcf7391',
    messagingSenderId: '217858776772',
    projectId: 'flutter-rpg-36622',
    storageBucket: 'flutter-rpg-36622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgRFXUq7mGWBtrLphWfklIjTLQUWJicWk',
    appId: '1:217858776772:ios:2e4831b8f42e0284cf7391',
    messagingSenderId: '217858776772',
    projectId: 'flutter-rpg-36622',
    storageBucket: 'flutter-rpg-36622.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3g8zbh4k0YYI86bMTk0uDdKM2LsnmcoU',
    appId: '1:217858776772:web:3b3abc4a76d96346cf7391',
    messagingSenderId: '217858776772',
    projectId: 'flutter-rpg-36622',
    authDomain: 'flutter-rpg-36622.firebaseapp.com',
    storageBucket: 'flutter-rpg-36622.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgRFXUq7mGWBtrLphWfklIjTLQUWJicWk',
    appId: '1:217858776772:ios:2e4831b8f42e0284cf7391',
    messagingSenderId: '217858776772',
    projectId: 'flutter-rpg-36622',
    storageBucket: 'flutter-rpg-36622.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3g8zbh4k0YYI86bMTk0uDdKM2LsnmcoU',
    appId: '1:217858776772:web:1376bcaefa8b1c5bcf7391',
    messagingSenderId: '217858776772',
    projectId: 'flutter-rpg-36622',
    authDomain: 'flutter-rpg-36622.firebaseapp.com',
    storageBucket: 'flutter-rpg-36622.appspot.com',
  );

}