// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:flutter_rpg/env.dart';

String androidGooglepiKey = Env.androidGoogleApiKey;
String iosGooglepiKey = Env.iosGoogleApiKey;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: androidGooglepiKey,
    appId: '1:217858776772:android:e2a537517fc7da8bcf7391',
    messagingSenderId: '217858776772',
    projectId: 'flutter-rpg-36622',
    storageBucket: 'flutter-rpg-36622.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: iosGooglepiKey,
    appId: '1:217858776772:ios:2e4831b8f42e0284cf7391',
    messagingSenderId: '217858776772',
    projectId: 'flutter-rpg-36622',
    storageBucket: 'flutter-rpg-36622.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );
}
